# values/joget-values.yaml
# Custom values for Joget deployment

# Number of replicas
replicaCount: 1

# Persistent Volume Configuration
pvc:
  accessMode: ReadWriteOnce
  storage: 10Gi
  storageClassName: managed-csi

# Image configuration
image:
  repository: jogetworkflow/joget-dx8-tomcat9
  pullPolicy: IfNotPresent
  tag: "8.0.21" # Use specific version instead of latest
  volumePath: /opt/joget/wflow

# Service configuration
service:
  type: ClusterIP
  http:
    port: 8080
  https:
    port: 9080

# Ingress configuration (can be enabled later)
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: joget.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Pod security context
podSecurityContext:
  fsGroup: 1000

# Container security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000

# Node selector (optional)
nodeSelector: {}

# Tolerations (optional)
tolerations: []

# Affinity (optional)
affinity: {}

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/jw"
