# values/joget-values.yaml
# Joget DX Configuration with Template Fix

# CRITICAL: These name overrides fix the template error
nameOverride: "joget-dx8"
fullnameOverride: "joget-dx8"

# Deployment Configuration
replicaCount: 1

# Persistent Volume Configuration
pvc:
  accessMode: ReadWriteOnce
  storage: 10Gi
  storageClassName: "managed-csi"

# Joget Image Configuration
image:
  repository: jogetworkflow/joget-dx8-tomcat9
  pullPolicy: IfNotPresent
  tag: "8.1.1"
  volumePath: /opt/joget/wflow

# Service Configuration
service:
  type: ClusterIP
  http:
    port: 8080
  https:
    port: 9080

# Ingress Configuration (disabled for development)
ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
  hosts:
    - host: joget.local
      paths:
        - path: /
          pathType: Prefix

# Resource Limits
resources:
  limits:
    memory: 2Gi
    cpu: 1000m
  requests:
    memory: 1Gi
    cpu: 500m

# Security Context
podSecurityContext:
  fsGroup: 0

securityContext:
  runAsUser: 1000
  runAsNonRoot: false

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod Annotations
podAnnotations:
  description: "Joget DX - Business Process & Workflow Engine"

# Environment Variables for Database Connection
extraEnvVars:
  - name: DB_HOST
    value: "postgresql"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "joget"
  - name: DB_USER
    value: "joget_user"
  - name: DB_PASSWORD
    value: "joget_password"

# Autoscaling (disabled for development)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Image Pull Secrets
imagePullSecrets: []

# Node Selection
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Host aliases for database connectivity
hostAliases: []

# Additional volumes
extraVolumes: []
extraVolumeMounts: []

# Probe configurations
livenessProbe:
  enabled: true
  httpGet:
    path: /jw
    port: 8080
  initialDelaySeconds: 180
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 6

readinessProbe:
  enabled: true
  httpGet:
    path: /jw
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

startupProbe:
  enabled: true
  httpGet:
    path: /jw
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
