# values/kobotoolbox-values.yaml - MINIMAL WORKING VERSION
# KoboToolbox Configuration - All critical settings handled by Helm parameters
shared:
  initContainers:
    - name: wait-db
      image: busybox:1.35  # Working image with proper shell
      command: ["/bin/sh"]
      args: 
        - "-c"
        - |
          echo "Waiting for PostgreSQL..."
          until nc -z ${POSTGRES_HOST} ${POSTGRES_PORT}; do
            echo "PostgreSQL not ready, waiting..."
            sleep 3
          done
          echo "PostgreSQL is ready!"
          
          echo "Waiting for MongoDB..."
          until nc -z ${KOBO_MONGO_HOST} ${KOBO_MONGO_PORT}; do
            echo "MongoDB not ready, waiting..."
            sleep 3
          done
          echo "MongoDB is ready!"
          
          echo "All databases are ready, proceeding..."
      env:
        - name: POSTGRES_HOST
          value: "kobotoolbox-postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        - name: KOBO_MONGO_HOST
          value: "kobotoolbox-mongodb"
        - name: KOBO_MONGO_PORT
          value: "27017"
# Basic resource configuration
general:
  # Most settings overridden by Helm parameters
  replicas: 1
  debug: false
  serviceType: ClusterIP

# Application images - use stable versions
kpi:
  image:
    name: kobotoolbox/kpi
    tag: "2.022.24d"  # From official values

kobocat:
  image:
    name: kobotoolbox/kobocat
    tag: "2.022.24a"  # From official values

enketo:
  image:
    name: enketo/enketo-express
    tag: "3.0.4"  # From official values
  replicas: 1

nginx:
  image:
    name: nginx
    tag: "1.21"  # From official values

# Service configuration
ingress:
  enabled: false

# Monitoring (disable for development)
uwsgiExporter:
  enabled: false

flower:
  enabled: false

probes:
  enabled: true

# Priority class (optional, can remove if not needed)
priorityClass: ""

# SMTP (disabled for development)
smtp:
  host: ""
  user: ""
  password: ""
  from: ""

# External services (disabled for development)
external:
  google:
    apiKey: ""
    analyticsToken: ""
  ravenDSN:
    kobocat: ""
    kpi: ""
    kpiJs: ""

# Sentry configuration
general:
  sentry:
    environment: development
