# values/kobotoolbox-values.yaml - FIXED VERSION
# Only override what's absolutely necessary since parameters handle most config

# Shared configuration for init containers and sidecars
shared:
  # Empty or minimal init containers to avoid the dockerize issue
  initContainers: []
  extraEnv:
    BACKUPS_DIR: /srv/backups
  extraSecretEnv: {}

# KPI specific environment variables (if needed beyond defaults)
kpi:
  extraEnv:
    # Use chart defaults mostly, add only if needed
    KOBO_SUPPORT_URL: "http://support.kobotoolbox.org/"
    EMAIL_FILE_PATH: "./emails"
    # CRITICAL: Configure Django to use PostGIS backend
    DATABASE_ENGINE: "django.contrib.gis.db.backends.postgis"
    DATABASES_DEFAULT_ENGINE: "django.contrib.gis.db.backends.postgis"
    POSTGIS_VERSION: "3.1"

# KoboCAT specific environment variables (if needed beyond defaults)
kobocat:
  extraEnv:
    # Use chart defaults mostly, add only if needed
    ENKETO_OFFLINE_SURVEYS: "True"
    # CRITICAL: Configure Django to use PostGIS backend
    DATABASE_ENGINE: "django.contrib.gis.db.backends.postgis"
    DATABASES_DEFAULT_ENGINE: "django.contrib.gis.db.backends.postgis"
    POSTGIS_VERSION: "3.1"

# Enketo specific configuration (use chart defaults)
enketo:
  # Use chart default API keys for development
  # Production should use secure random keys
  logoSource: ""
