# values/kobotoolbox-values.yaml - MINIMAL WORKING VERSION
# KoboToolbox Configuration - All critical settings handled by Helm parameters

# Basic resource configuration
general:
  # Most settings overridden by Helm parameters
  replicas: 1
  debug: false
  serviceType: ClusterIP

# Application images - use stable versions
kpi:
  image:
    name: kobotoolbox/kpi
    tag: "2.022.24d"  # From official values

kobocat:
  image:
    name: kobotoolbox/kobocat
    tag: "2.022.24a"  # From official values

enketo:
  image:
    name: enketo/enketo-express
    tag: "3.0.4"  # From official values
  replicas: 1

nginx:
  image:
    name: nginx
    tag: "1.21"  # From official values

# Service configuration
ingress:
  enabled: false

# Monitoring (disable for development)
uwsgiExporter:
  enabled: false

flower:
  enabled: false

probes:
  enabled: true

# Priority class (optional, can remove if not needed)
priorityClass: ""

# SMTP (disabled for development)
smtp:
  host: ""
  user: ""
  password: ""
  from: ""

# External services (disabled for development)
external:
  google:
    apiKey: ""
    analyticsToken: ""
  ravenDSN:
    kobocat: ""
    kpi: ""
    kpiJs: ""

# Sentry configuration
general:
  sentry:
    environment: development
