# values/postgresql-values.yaml - DEVELOPMENT VERSION

# PostgreSQL Authentication
auth:
  postgresPassword: "dev-postgres-password"  # Simple for development
  database: "superset"
  username: "superset_user"
  password: "dev-user-password"  # Simple for development

# Primary PostgreSQL instance configuration
primary:
  # Persistence configuration
  persistence:
    enabled: true
    size: 10Gi  # Smaller for development
    storageClass: "managed-csi"
    accessModes:
      - ReadWriteOnce
  
  # Development resource limits
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m
  
  # Service configuration
  service:
    ports:
      postgresql: 5432

# DISABLE read replicas for development
readReplicas:
  replicaCount: 0

# Security and permissions
volumePermissions:
  enabled: true

# DISABLE metrics for development (avoids ServiceMonitor error)
metrics:
  enabled: false
  serviceMonitor:
    enabled: false

# DISABLE backup for development
backup:
  enabled: false

# Security context
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

podSecurityContext:
  enabled: true
  fsGroup: 1001