# values/postgresql-values.yaml - JOGET VERSION
# PostgreSQL Authentication for Joget
auth:
  postgresPassword: "dev-postgres-password"
  database: "joget" # Changed to joget database
  username: "joget_user" # Changed to joget user
  password: "joget_password" # Joget user password

# Primary PostgreSQL instance configuration
primary:
  # Persistence configuration
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "managed-csi"
    accessModes:
      - ReadWriteOnce

  # Development resource limits
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m

  # Service configuration
  service:
    ports:
      postgresql: 5432

  # Initialize database with Joget schema
  initdb:
    scripts:
      01-create-joget-db.sql: |
        -- Create Joget database and user automatically
        CREATE DATABASE joget;
        CREATE USER joget_user WITH PASSWORD 'joget_password';
        GRANT ALL PRIVILEGES ON DATABASE joget TO joget_user;
        ALTER USER joget_user CREATEDB;

        -- Connect to joget database and set permissions
        \c joget;
        GRANT ALL ON SCHEMA public TO joget_user;
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO joget_user;
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO joget_user;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO joget_user;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO joget_user;

# DISABLE read replicas for development
readReplicas:
  replicaCount: 0

# Security and permissions
volumePermissions:
  enabled: true

# DISABLE metrics for development
metrics:
  enabled: false
  serviceMonitor:
    enabled: false

# DISABLE backup for development
backup:
  enabled: false

# Security context
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

podSecurityContext:
  enabled: true
  fsGroup: 1001
