# Superset configuration overrides
configOverrides:
  secret: |
    import os
    # Debug environment variables
    print(f"DB_USER: {os.environ.get('DB_USER')}")
    print(f"DB_PASS: {os.environ.get('DB_PASS')}")
    print(f"DB_HOST: {os.environ.get('DB_HOST')}")
    print(f"DB_PORT: {os.environ.get('DB_PORT')}")
    print(f"DB_NAME: {os.environ.get('DB_NAME')}")
    SECRET_KEY = os.environ.get('SUPERSET_SECRET_KEY', 'fallback-secret')
    # Enable CORS for development (restrict in production)
    ENABLE_CORS = True
    CORS_OPTIONS = {
      'supports_credentials': True,
      'allow_headers': ['*'],
      'resources': ['*'],
      'origins': ['http://localhost:8088']
    }
    # Define SQLALCHEMY_DATABASE_URI
    SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{os.environ.get('DB_USER')}:{os.environ.get('DB_PASS')}@{os.environ.get('DB_HOST')}:{os.environ.get('DB_PORT')}/{os.environ.get('DB_NAME')}"

# Global service account for Azure Workload Identity
serviceAccountName: "superset-workload-identity"

# Service account configuration
serviceAccount:
  create: false

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    existingSecret: "superset-secrets"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "postgres-password"
    database: "superset"
    username: "superset"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "managed-csi"
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
    podLabels:
      azure.workload.identity/use: "true"
    extraVolumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "superset-secrets"
    extraVolumeMounts:
    - name: secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "managed-csi"
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 128Mi
        cpu: 100m

# Global labels for workload identity
extraLabels:
  azure.workload.identity/use: "true"

# Global CSI volume for Key Vault secrets
extraVolumes:
- name: secrets-store
  csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: "superset-secrets"

extraVolumeMounts:
- name: secrets-store
  mountPath: "/mnt/secrets-store"
  readOnly: true

# Global environment variables
extraEnv:
  SUPERSET_SECRET_KEY:
    valueFrom:
      secretKeyRef:
        name: superset-secrets
        key: secret-key
  DB_USER:
    value: "superset"
  DB_HOST:
    value: "apache-superset-postgresql"
  DB_PORT:
    value: "5432"
  DB_NAME:
    value: "superset"
  DB_PASS:
    valueFrom:
      secretKeyRef:
        name: superset-secrets
        key: postgres-password

# Superset Node configuration
supersetNode:
  replicaCount: 1
  podLabels:
    azure.workload.identity/use: "true"
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m
  command:
  - /bin/sh
  - -c
  - |
    # Debug environment variables
    echo "DB_PASS: $DB_PASS"
    # Start Superset
    . {{ .Values.configMountPath }}/superset_bootstrap.sh; gunicorn --bind "0.0.0.0:{{ .Values.service.port }}" --access-logfile '-' --error-logfile '-' --workers 1 --worker-class gthread --threads 20 --timeout 60 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100 --preload "superset.app:create_app()"

# Superset Worker configuration
supersetWorker:
  replicaCount: 1
  podLabels:
    azure.workload.identity/use: "true"
  resources:
    limits:
      memory: 512Mi
      cpu: 250m
    requests:
      memory: 256Mi
      cpu: 125m
  extraEnv:
    DB_USER:
      value: "superset"
    DB_HOST:
      value: "apache-superset-postgresql"
    DB_PORT:
      value: "5432"
    DB_NAME:
      value: "superset"
    DB_PASS:
      valueFrom:
        secretKeyRef:
          name: superset-secrets
          key: postgres-password

# Disable Celery Beat
supersetCeleryBeat:
  enabled: false

# Initial setup with admin credentials
init:
  loadExamples: true
  createAdmin: true
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@example.com
  podLabels:
    azure.workload.identity/use: "true"
  extraEnv:
    SUPERSET_ADMIN_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: superset-secrets
          key: admin-password

service:
  type: ClusterIP
  port: 8088

ingress:
  enabled: false

runAsUser: 1000

bootstrapScript: |
  #!/bin/bash
  pip install --no-cache-dir \
    psycopg2-binary \
    redis \
    flask-cors