# values/superset-values.yaml - DEVELOPMENT VERSION

# Superset configuration overrides
configOverrides:
  secret: |
    SECRET_KEY = 'dev-secret-key-change-for-production'
    # Enable CORS for development
    ENABLE_CORS = True
    CORS_OPTIONS = {
      'supports_credentials': True,
      'allow_headers': ['*'],
      'resources': ['*'],
      'origins': ['http://localhost:8088']
    }

# ENABLE internal dependencies (much simpler!)
postgresql:
  enabled: true
  auth:
    postgresPassword: "superset-postgres-password"
    database: "superset"
    username: "superset"
    password: "superset"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "managed-csi"
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m

redis:
  enabled: true
  auth:
    enabled: false # Disable auth for simplicity
  master:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "managed-csi"
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 128Mi
        cpu: 100m

# Superset Node (web server) configuration
supersetNode:
  replicaCount: 1
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m
  podDisruptionBudget:
    enabled: false
  autoscaling:
    enabled: false

# Superset Worker (Celery) configuration
supersetWorker:
  replicaCount: 1
  resources:
    limits:
      memory: 512Mi
      cpu: 250m
    requests:
      memory: 256Mi
      cpu: 125m
  podDisruptionBudget:
    enabled: false
  autoscaling:
    enabled: false

# Disable Celery Beat for development
supersetCeleryBeat:
  enabled: false

# Initial setup configuration
init:
  loadExamples: true
  createAdmin: true
  adminUser:
    username: admin
    firstname: Admin
    lastname: User
    email: admin@example.com
    password: admin

# Service configuration
service:
  type: ClusterIP
  port: 8088

# Ingress configuration (disabled for development)
ingress:
  enabled: false

# Security context
runAsUser: 1000

# Bootstrap script with required packages
bootstrapScript: |
  #!/bin/bash
  pip install --no-cache-dir \
    psycopg2-binary \
    redis \
    flask-cors
