# Namespace (ensure it exists)
apiVersion: v1
kind: Namespace
metadata:
  name: joget
---
# RBAC for Joget Clustering
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: joget
  name: joget-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: joget-cluster-binding
  namespace: joget
subjects:
- kind: ServiceAccount
  name: joget
  namespace: joget
roleRef:
  kind: Role
  name: joget-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# Persistent Volume Claim for Joget data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joget-data-pvc
  namespace: joget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 10Gi
---
# ConfigMap for Joget configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: joget-config
  namespace: joget
data:
  DATASOURCE_DRIVER: "org.postgresql.Driver"
  DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/joget?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
  DATASOURCE_USERNAME: "joget_user"
  JAVA_OPTS: "-Xmx2048m -Xms512m -XX:MaxMetaspaceSize=512m"
---
# Secret for database password
apiVersion: v1
kind: Secret
metadata:
  name: joget-secrets
  namespace: joget
type: Opaque
data:
  DATASOURCE_PASSWORD: am9nZXRfcGFzc3dvcmQ=  # 'joget_password' encoded
---
# Service Account for clustering
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joget
  namespace: joget
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joget
  namespace: joget
  labels:
    app: joget
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joget
  template:
    metadata:
      labels:
        app: joget
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/jw"
    spec:
      serviceAccountName: joget
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      # Wait for PostgreSQL to be ready
      - name: wait-for-postgresql
        image: postgres:13-alpine
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgresql -p 5432 -U joget_user; do
            echo "PostgreSQL is not ready yet, waiting..."
            sleep 5
          done
          echo "PostgreSQL is ready!"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: joget-secrets
              key: DATASOURCE_PASSWORD
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000

      # Setup Joget configuration for DX8
      - name: setup-joget-config
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Setting up Joget DX8 configuration..."
          mkdir -p /data/wflow
          mkdir -p /home/tomcat/wflow

          # Create app_datasource.properties
          echo "currentProfile=postgresql" > /data/wflow/app_datasource.properties

          # Create app_datasource-postgresql.properties
          cat > /data/wflow/app_datasource-postgresql.properties << EOF
          workflowUser=joget_user
          workflowPassword=\$(cat /run/secrets/joget-secrets/DATASOURCE_PASSWORD)
          workflowDriver=org.postgresql.Driver
          workflowUrl=jdbc:postgresql://postgresql:5432/joget?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          profileName=postgresql
          EOF

          # Create app_datasource-default.properties
          cat > /data/wflow/app_datasource-default.properties << EOF
          workflowDriver=org.hsqldb.jdbcDriver
          workflowUrl=jdbc:hsqldb:file:/home/tomcat/wflow/db/jwdb;shutdown=true;hsqldb.write_delay=false;hsqldb.log_data=false
          workflowUser=sa
          workflowPassword=
          profileName=
          EOF

          # Copy config files to Joget default location
          cp /data/wflow/*.properties /home/tomcat/wflow/
          chmod -R 755 /data/wflow /home/tomcat/wflow

          echo "Configuration files created successfully:"
          ls -la /data/wflow/
          ls -la /home/tomcat/wflow/
          echo "Setup complete!"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: joget-data
          mountPath: /data
        - name: tomcat-home
          mountPath: /home/tomcat
        - name: joget-secrets
          mountPath: /run/secrets/joget-secrets
          readOnly: true
      containers:
      - name: joget
        image: jogetworkflow/joget-dx8-tomcat9:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9080
          name: https
          protocol: TCP
        - containerPort: 4000
          name: cluster
          protocol: TCP
        env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: joget-config
              key: JAVA_OPTS
        - name: CATALINA_OPTS
          value: "-Djoget.cluster.enabled=true -Dtomcat.clustering.enabled=true -Djava.net.preferIPv4Stack=true"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_LABELS
          value: "app=joget"
        - name: WFLOW_HOME
          value: "/home/tomcat/wflow"
        volumeMounts:
        - name: joget-data
          mountPath: /data
        - name: tomcat-home
          mountPath: /home/tomcat
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /jw
            port: 8080
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /jw
            port: 8080
          initialDelaySeconds: 480
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
        startupProbe:
          httpGet:
            path: /jw
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 60
      volumes:
      - name: joget-data
        persistentVolumeClaim:
          claimName: joget-data-pvc
      - name: tomcat-home
        emptyDir: {}
      - name: joget-secrets
        secret:
          secretName: joget-secrets
      restartPolicy: Always
---
# Headless Service for clustering
apiVersion: v1
kind: Service
metadata:
  name: joget-cluster
  namespace: joget
  labels:
    app: joget
spec:
  clusterIP: None
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: cluster
  selector:
    app: joget
---
# Regular Service for external access
apiVersion: v1
kind: Service
metadata:
  name: joget-service
  namespace: joget
  labels:
    app: joget
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 9080
    protocol: TCP
    name: https
  selector:
    app: joget