# Complete Joget DX8 Production Setup with Clustering
# RBAC for Joget Clustering
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: joget
  name: joget-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: joget-cluster-binding
  namespace: joget
subjects:
- kind: ServiceAccount
  name: joget
  namespace: joget
roleRef:
  kind: Role
  name: joget-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# Persistent Volume Claim for Joget data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joget-data-pvc
  namespace: joget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 10Gi
---
# ConfigMap for Joget configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: joget-config
  namespace: joget
data:
  DATASOURCE_DRIVER: "org.postgresql.Driver"
  DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/joget?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
  DATASOURCE_USERNAME: "joget_user"
  JAVA_OPTS: "-Xmx2048m -Xms512m -XX:MaxMetaspaceSize=512m"
---
# Secret for database password
apiVersion: v1
kind: Secret
metadata:
  name: joget-secrets
  namespace: joget
type: Opaque
data:
  DATASOURCE_PASSWORD: am9nZXRfcGFzc3dvcmQ=  # 'joget_password' encoded
---
# Service Account for clustering
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joget
  namespace: joget
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joget
  namespace: joget
  labels:
    app: joget
spec:
  replicas: 1  # Start with 1, scale later
  selector:
    matchLabels:
      app: joget
  template:
    metadata:
      labels:
        app: joget
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/jw"
    spec:
      serviceAccountName: joget
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      # Wait for PostgreSQL to be ready
      - name: wait-for-postgresql
        image: postgres:13-alpine
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgresql -p 5432 -U joget_user; do
            echo "PostgreSQL is not ready yet, waiting..."
            sleep 5
          done
          echo "PostgreSQL is ready!"
        env:
        - name: PGPASSWORD
          value: "joget_password"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000

      # Setup Joget configuration for DX8 - Fixed path
      - name: setup-joget-config
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Setting up Joget DX8 configuration..."

          # Create directories for both locations (persistent and default)
          mkdir -p /data/wflow
          mkdir -p /home/tomcat/wflow

          # Create app_datasource.properties - points to postgresql profile
          cat > /data/wflow/app_datasource.properties << 'EOF'
          currentProfile=postgresql
          EOF

          # Create app_datasource-postgresql.properties - PostgreSQL connection details
          cat > /data/wflow/app_datasource-postgresql.properties << 'EOF'
          workflowUser=joget_user
          workflowPassword=joget_password
          workflowDriver=org.postgresql.Driver
          workflowUrl=jdbc\:postgresql\://postgresql:5432/joget
          profileName=postgresql
          EOF

          # Create app_datasource-default.properties - Required by Joget
          cat > /data/wflow/app_datasource-default.properties << 'EOF'
          workflowDriver=org.hsqldb.jdbcDriver
          workflowUrl=jdbc\:hsqldb\:file\:${wflow.home}/db/jwdb;shutdown\=true;hsqldb.write_delay\=false;hsqldb.log_data\=false
          workflowUser=sa
          workflowPassword=
          profileName=
          EOF

          # Copy config files to where Joget DX8 actually looks
          cp /data/wflow/*.properties /home/tomcat/wflow/

          # Set proper permissions for both locations
          chmod -R 755 /data/wflow/
          chmod -R 755 /home/tomcat/wflow/

          echo "Configuration files created successfully:"
          echo "=== Persistent storage (/data/wflow) ==="
          ls -la /data/wflow/
          echo "=== Joget default location (/home/tomcat/wflow) ==="
          ls -la /home/tomcat/wflow/
          echo "Setup complete!"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: joget-data
          mountPath: /data
        - name: tomcat-home
          mountPath: /home/tomcat
          
      containers:
      - name: joget
        image: jogetworkflow/joget-dx8-tomcat9:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9080
          name: https
          protocol: TCP
        - containerPort: 4000
          name: cluster
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: "-Xmx2048m -Xms512m -XX:MaxMetaspaceSize=512m"
        # ENABLE clustering but fix the namespace issue
        - name: CATALINA_OPTS
          value: "-Djoget.cluster.enabled=true -Dtomcat.clustering.enabled=true -Djava.net.preferIPv4Stack=true"
        # Override the wrong namespace from DX8 image
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Set the correct label selector
        - name: KUBERNETES_LABELS
          value: "app=joget"
        # Set WFLOW_HOME to the location where we actually put the config
        - name: WFLOW_HOME
          value: "/home/tomcat/wflow"
        volumeMounts:
        - name: joget-data
          mountPath: /data
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        # Health checks
        # livenessProbe:
        #   httpGet:
        #     path: /jw
        #     port: 8080
        #   initialDelaySeconds: 600
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        #   failureThreshold: 5
        # readinessProbe:
        #   httpGet:
        #     path: /jw
        #     port: 8080
        #   initialDelaySeconds: 480
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 10
        # startupProbe:
        #   httpGet:
        #     path: /jw
        #     port: 8080
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        #   failureThreshold: 60
      volumes:
      - name: joget-data
        persistentVolumeClaim:
          claimName: joget-data-pvc
      - name: tomcat-home
        emptyDir: {}  # Temporary volume for tomcat home directory
      restartPolicy: Always
---
# Headless Service for clustering (pod discovery)
apiVersion: v1
kind: Service
metadata:
  name: joget-cluster
  namespace: joget
  labels:
    app: joget
spec:
  clusterIP: None  # Headless service for clustering
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: cluster
  selector:
    app: joget
---
# Regular Service for external access
apiVersion: v1
kind: Service
metadata:
  name: joget-service
  namespace: joget
  labels:
    app: joget
spec:
  type: LoadBalancer  # For easy external access
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 9080
    protocol: TCP
    name: https
  selector:
    app: joget