resource_group_name = "rg-aks-data-dev"
location            = "West Europe"
cluster_name        = "aks-data-dev-test"
kubernetes_version  = "1.32.5"
system_node_count   = 2
subscription_id     = "a6de3cd4-15d9-4c7f-87ac-9a4399b01e45"
workload_identity_namespace        = "default"
workload_identity_service_account  = "workload-identity-sa"
keyvaultname       = "kv-aks-data-dev-95548452"