# templates/secrets-template.yaml
# This file contains secret templates that will be populated by CI/CD pipeline

---
# PostgreSQL Production Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: {{ .Values.namespaces.database | default "joget" }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Values.global.instance }}
    app.kubernetes.io/managed-by: {{ .Values.global.managedBy | default "argocd" }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresql.adminPassword | b64enc }}
  username: {{ .Values.secrets.postgresql.username | b64enc }}
  password: {{ .Values.secrets.postgresql.userPassword | b64enc }}
  replication-password: {{ .Values.secrets.postgresql.replicationPassword | b64enc }}

---
# Superset Production Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: {{ .Values.namespaces.superset | default "superset" }}
  labels:
    app.kubernetes.io/name: superset
    app.kubernetes.io/instance: {{ .Values.global.instance }}
    app.kubernetes.io/managed-by: {{ .Values.global.managedBy | default "argocd" }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.superset.secretKey | b64enc }}
  postgres-password: {{ .Values.secrets.superset.postgresPassword | b64enc }}
  redis-password: {{ .Values.secrets.superset.redisPassword | b64enc }}
  admin-password: {{ .Values.secrets.superset.adminPassword | b64enc }}

---
# KoboToolbox Production Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: kobotoolbox-secrets
  namespace: {{ .Values.namespaces.kobotoolbox | default "kobotoolbox" }}
  labels:
    app.kubernetes.io/name: kobotoolbox
    app.kubernetes.io/instance: {{ .Values.global.instance }}
    app.kubernetes.io/managed-by: {{ .Values.global.managedBy | default "argocd" }}
type: Opaque
data:
  django-secret: {{ .Values.secrets.kobotoolbox.djangoSecret | b64enc }}
  superuser-password: {{ .Values.secrets.kobotoolbox.superuserPassword | b64enc }}
  postgres-password: {{ .Values.secrets.kobotoolbox.postgresPassword | b64enc }}
  redis-password: {{ .Values.secrets.kobotoolbox.redisPassword | b64enc }}
  mongo-root-password: {{ .Values.secrets.kobotoolbox.mongoRootPassword | b64enc }}
  mongo-password: {{ .Values.secrets.kobotoolbox.mongoPassword | b64enc }}

---
# NiFi Production Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: nifi-secrets
  namespace: {{ .Values.namespaces.nifi | default "nifi-prod" }}
  labels:
    app.kubernetes.io/name: nifi
    app.kubernetes.io/instance: {{ .Values.global.instance }}
    app.kubernetes.io/managed-by: {{ .Values.global.managedBy | default "argocd" }}
type: Opaque
data:
  sensitive-key: {{ .Values.secrets.nifi.sensitiveKey | b64enc }}
  keystore-password: {{ .Values.secrets.nifi.keystorePassword | b64enc }}
  truststore-password: {{ .Values.secrets.nifi.truststorePassword | b64enc }}
  admin-password: {{ .Values.secrets.nifi.adminPassword | b64enc }}

---
# Joget Production Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: joget-secrets
  namespace: {{ .Values.namespaces.joget | default "joget" }}
  labels:
    app.kubernetes.io/name: joget
    app.kubernetes.io/instance: {{ .Values.global.instance }}
    app.kubernetes.io/managed-by: {{ .Values.global.managedBy | default "argocd" }}
type: Opaque
data:
  datasource-password: {{ .Values.secrets.joget.datasourcePassword | b64enc }}