# # argocd/joget-app.yaml
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: joget
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "2" # Deploy after PostgreSQL
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - repoURL: https://jogetworkflow.github.io/helm-joget/charts/
#       targetRevision: "*"
#       chart: joget
#       helm:
#         releaseName: joget-dx8 # Important: This helps with template naming
#         parameters:
#           - name: nameOverride
#             value: "joget-dx8"
#           - name: fullnameOverride
#             value: "joget-dx8"
#         valueFiles:
#           - $values/values/joget-values.yaml
#     - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
#       targetRevision: HEAD
#       ref: values
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: joget
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: false
#     syncOptions:
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 5m
#   revisionHistoryLimit: 3
