apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joget
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/jogetworkflow/helm-joget.git
      targetRevision: main
      path: .
      helm:
        parameters:
          # Basic configuration
          - name: replicaCount
            value: "1"

          # Image configuration
          - name: image.repository
            value: "jogetworkflow/joget-dx8-tomcat9"
          - name: image.tag
            value: "latest"
          - name: image.pullPolicy
            value: "IfNotPresent"

          # Storage configuration
          - name: pvc.storage
            value: "10Gi"
          - name: pvc.storageClassName
            value: "managed-csi"
          - name: pvc.accessMode
            value: "ReadWriteOnce"

          # Service configuration
          - name: service.type
            value: "ClusterIP"
          - name: service.http.port
            value: "8080"
          - name: service.https.port
            value: "9080"

          # Ingress configuration (disabled for now)
          - name: ingress.enabled
            value: "false"

          # Resource limits (optional)
          - name: resources.limits.cpu
            value: "2000m"
          - name: resources.limits.memory
            value: "4Gi"
          - name: resources.requests.cpu
            value: "500m"
          - name: resources.requests.memory
            value: "1Gi"

        valueFiles:
          - $values/values/joget-values.yaml
    - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: joget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 15m
  revisionHistoryLimit: 3
