apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joget
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4" # After PostgreSQL (wave 1)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
    targetRevision: HEAD
    path: manifests/joget
  destination:
    server: https://kubernetes.default.svc
    namespace: joget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Replace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 15m
  revisionHistoryLimit: 3
