# argocd/kobotoolbox-app.yaml - FINAL WORKING VERSION
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kobotoolbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://one-acre-fund.github.io/oaf-public-charts
      targetRevision: "0.7.4"
      chart: kobotoolbox
      helm:
        # THE KEY FIX: Override the global storageClass
        parameters:
          - name: global.storageClass
            value: "managed-csi"
          # Also override Redis password to avoid issues
          - name: global.redis.password
            value: "redis-password-123"
          # Override domain settings
          - name: general.externalDomain
            value: "kobotoolbox.local"
          - name: general.externalScheme
            value: "http"
          # Set admin credentials
          - name: general.superUser.username
            value: "admin"
          - name: general.superUser.password
            value: "admin123"
          # Enable media storage
          - name: general.mediaStorage.enabled
            value: "false"
          # PostgreSQL settings
          - name: postgresql.auth.postgresPassword
            value: "postgres-admin-123"
          - name: postgresql.auth.password
            value: "kobo-user-123"
          # MongoDB settings
          - name: mongodb.auth.rootPassword
            value: "mongo-admin-123"
          - name: mongodb.auth.password
            value: "mongo-user-123"

        valueFiles:
          - $values/values/kobotoolbox-values.yaml
    - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kobotoolbox
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
  revisionHistoryLimit: 3
