apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kobotoolbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Manifests for SecretProviderClass and ServiceAccount
    - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
      targetRevision: HEAD
      path: manifests/kobotoolbox
    # Helm chart
    - repoURL: https://github.com/AzizBenDhiab/oaf-public-charts.git
      targetRevision: main
      path: charts/kobotoolbox
      helm:
        parameters:
          # CRITICAL: Override the hardcoded global.storageClass
          - name: global.storageClass
            value: "managed-csi"

          # Redis configuration - chart doesn't seem to support existing secrets for Redis password
          # You may need to modify the chart or use a different approach for Redis secrets
          - name: global.redis.password
            value: "redis-secure-password-2024"
          - name: rediscache.enabled
            value: "true"
          - name: rediscache.usePassword
            value: "true"
          - name: rediscache.architecture
            value: "standalone"
          - name: redismain.enabled
            value: "true"
          - name: redismain.usePassword
            value: "true"
          - name: redismain.architecture
            value: "standalone"

          # General configuration
          - name: general.externalDomain
            value: "kobotoolbox.local"
          - name: general.externalScheme
            value: "http"
          - name: general.externalPort
            value: ""
          - name: general.replicas
            value: "1"
          - name: general.debug
            value: "false"
          - name: general.serviceType
            value: "ClusterIP"
          - name: general.forceInternal
            value: "false"

          # Super user configuration - chart doesn't appear to support existing secrets
          - name: general.superUser.username
            value: "admin"
          - name: general.superUser.password
            value: "KoboAdmin2024!"

          # Support email
          - name: general.supportEmail
            value: "support@kobotoolbox.local"

          # Django secret - chart expects a direct string value
          - name: general.djangoSecret
            value: "KoboProductionSecret2024ChangeInProduction"

          # Media storage configuration
          - name: general.mediaStorage.enabled
            value: "false"
          - name: general.mediaStorage.size
            value: "10Gi"
          - name: general.mediaStorage.storageClass
            value: "managed-csi"
          - name: general.mediaStorage.accessMode
            value: "ReadWriteOnce"

          # Sentry configuration
          - name: general.sentry.environment
            value: "production"

          # PostgreSQL configuration - using existing secret if chart supports it
          - name: postgresql.enabled
            value: "true"
          - name: postgresql.kobocatDatabase
            value: "kobocat"
          - name: postgresql.kpiDatabase
            value: "koboform"
          - name: postgresql.auth.existingSecret
            value: "kobotoolbox-secrets"
          - name: postgresql.auth.secretKeys.adminPasswordKey
            value: "postgres-admin-password"
          - name: postgresql.auth.secretKeys.userPasswordKey
            value: "postgres-user-password"
          - name: postgresql.auth.username
            value: "postgres"

          # MongoDB configuration - using existing secret if chart supports it
          - name: mongodb.enabled
            value: "true"
          - name: mongodb.auth.existingSecret
            value: "kobotoolbox-secrets"
          - name: mongodb.auth.secretKeys.rootPasswordKey
            value: "mongo-root-password"
          - name: mongodb.auth.secretKeys.userPasswordKey
            value: "mongo-user-password"
          - name: mongodb.auth.username
            value: "kobo"
          - name: mongodb.auth.database
            value: "formhub"

          # Application image tags (use chart defaults or override)
          - name: kpi.image.tag
            value: "2.022.24d"
          - name: kobocat.image.tag
            value: "2.022.24a"
          - name: enketo.image.tag
            value: "3.0.4"
          - name: nginx.image.tag
            value: "1.21"

          # Enketo configuration
          - name: enketo.replicas
            value: "1"
          - name: enketo.subdomain
            value: "ee"

          # KPI subdomain
          - name: kpi.subdomain
            value: "kobo"

          # KoboCAT subdomain
          - name: kobocat.subdomain
            value: "kc"

          # Ingress (disabled)
          - name: ingress.enabled
            value: "false"

          # Monitoring (disabled for now)
          - name: uwsgiExporter.enabled
            value: "false"
          - name: flower.enabled
            value: "false"

          # Probes (enabled)
          - name: probes.enabled
            value: "true"

          # Priority class
          - name: priorityClass
            value: ""

          # SMTP (disabled for development)
          - name: smtp.host
            value: ""
          - name: smtp.user
            value: ""
          - name: smtp.password
            value: ""
          - name: smtp.from
            value: ""

          # External services (disabled)
          - name: external.google.apiKey
            value: ""
          - name: external.google.analyticsToken
            value: ""
          - name: external.ravenDSN.kobocat
            value: ""
          - name: external.ravenDSN.kpi
            value: ""
          - name: external.ravenDSN.kpiJs
            value: ""

          # Service account configuration (for workload identity)
          - name: serviceAccount.create
            value: "false"
          - name: serviceAccount.name
            value: "kobotoolbox-workload-identity"

          # Workload identity labels
          - name: podLabels.azure\.workload\.identity/use
            value: "true"

        valueFiles:
          - $values/values/kobotoolbox-values.yaml
    # Values repository
    - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kobotoolbox
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    #   allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 15m
  revisionHistoryLimit: 3