# argocd/kobotoolbox-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kobotoolbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # Deploy after other applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://one-acre-fund.github.io/oaf-public-charts
      targetRevision: "0.7.4" # Latest stable version
      chart: kobotoolbox
      helm:
        valueFiles:
          - $values/values/kobotoolbox-values.yaml
    - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kobotoolbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
  revisionHistoryLimit: 3
