apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    # Source 1: Helm chart pour Prometheus/Grafana/AlertManager
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "56.8.0"
      chart: kube-prometheus-stack
      helm:
        values: |
          # Grafana Configuration
          grafana:
            enabled: true
            adminPassword: admin123
            persistence:
              enabled: true
              size: 10Gi
              storageClassName: managed-csi
            service:
              type: ClusterIP
            grafana.ini:
              server:
                domain: grafana.local
                root_url: http://grafana.local
              security:
                allow_embedding: true
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
            dashboards:
              default:
                # Kubernetes Cluster Monitoring
                kubernetes-cluster:
                  gnetId: 7249
                  revision: 1
                  datasource: Prometheus
                # Node Exporter Dashboard
                node-exporter:
                  gnetId: 1860
                  revision: 27
                  datasource: Prometheus
                # Kubernetes Pod Monitoring
                kubernetes-pods:
                  gnetId: 6417
                  revision: 1
                  datasource: Prometheus

          # Prometheus Configuration
          prometheus:
            enabled: true
            prometheusSpec:
              retention: 30d
              retentionSize: 45GB
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: managed-csi
                    resources:
                      requests:
                        storage: 50Gi
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
              ruleSelectorNilUsesHelmValues: false
              resources:
                requests:
                  memory: 2Gi
                  cpu: 500m
                limits:
                  memory: 4Gi
                  cpu: 1000m
            service:
              type: ClusterIP

          # AlertManager Configuration
          alertmanager:
            enabled: true
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: managed-csi
                    resources:
                      requests:
                        storage: 5Gi
              resources:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
                  cpu: 100m
            service:
              type: ClusterIP
            config:
              global:
                resolve_timeout: 5m
              route:
                group_by: ['alertname', 'cluster', 'service']
                group_wait: 10s
                group_interval: 10s
                repeat_interval: 12h
                receiver: 'default'
                routes:
                - match:
                    alertname: DeadMansSwitch
                  receiver: 'null'
              receivers:
              - name: 'default'
                webhook_configs:
                - url: 'http://localhost:5001/'
                  send_resolved: true
              - name: 'null'

          # Node Exporter
          nodeExporter:
            enabled: true

          # Kube State Metrics
          kubeStateMetrics:
            enabled: true

          # Prometheus Operator
          prometheusOperator:
            enabled: true

          # Default Rules and Alerts
          defaultRules:
            create: true
            rules:
              alertmanager: true
              etcd: true
              configReloaders: true
              general: true
              k8s: true
              kubeApiserver: true
              kubeApiserverAvailability: true
              kubeApiserverSlos: true
              kubelet: true
              kubeProxy: true
              kubePrometheusGeneral: true
              kubePrometheusNodeRecording: true
              kubernetesApps: true
              kubernetesResources: true
              kubernetesStorage: true
              kubernetesSystem: true
              network: true
              node: true
              nodeExporterAlerting: true
              nodeExporterRecording: true
              prometheus: true
              prometheusOperator: true

    # Source 2: Vos manifests personnalisés (ServiceMonitors, AlertRules)
    - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
      targetRevision: HEAD
      path: manifests/monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
