apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    # Source 1: Helm chart for Prometheus/Grafana/AlertManager
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "56.8.0"
      chart: kube-prometheus-stack
      helm:
        values: |
          # Grafana Configuration with Azure Key Vault
          grafana:
            enabled: true
            admin:
              existingSecret: "monitoring-secrets"
              passwordKey: grafana-password
            persistence:
              enabled: true
              size: 10Gi
              storageClassName: managed-csi
            service:
              type: ClusterIP
            # Use workload identity service account
            serviceAccount:
              create: false
              name: monitoring-workload-identity
            # Add workload identity labels and CSI volume
            podLabels:
              azure.workload.identity/use: "true"
            extraVolumes:
            - name: secrets-store
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "monitoring-secrets"
            extraVolumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
            grafana.ini:
              server:
                domain: grafana.local
                root_url: http://grafana.local
              security:
                allow_embedding: true
                # Use secret from Key Vault for session security
                secret_key: "$__file{/mnt/secrets-store/prometheus-secret}"
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
            dashboards:
              default:
                # Kubernetes Cluster Monitoring
                kubernetes-cluster:
                  gnetId: 7249
                  revision: 1
                  datasource: Prometheus
                # Node Exporter Dashboard
                node-exporter:
                  gnetId: 1860
                  revision: 27
                  datasource: Prometheus
                # Kubernetes Pod Monitoring
                kubernetes-pods:
                  gnetId: 6417
                  revision: 1
                  datasource: Prometheus
                # PostgreSQL Dashboard
                postgresql:
                  gnetId: 9628
                  revision: 7
                  datasource: Prometheus
                # Kubernetes Deployment Dashboard
                kubernetes-deployments:
                  gnetId: 8588
                  revision: 1
                  datasource: Prometheus
                # JVM Dashboard (for NiFi, Superset)
                jvm-overview:
                  gnetId: 4701
                  revision: 5
                  datasource: Prometheus

          # Prometheus Configuration with workload identity
          prometheus:
            enabled: true
            serviceAccount:
              create: false
              name: monitoring-workload-identity
            prometheusSpec:
              retention: 30d
              retentionSize: 45GB
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: managed-csi
                    resources:
                      requests:
                        storage: 50Gi
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
              ruleSelectorNilUsesHelmValues: false
              # Add workload identity labels and CSI volume
              podMetadata:
                labels:
                  azure.workload.identity/use: "true"
              volumes:
              - name: secrets-store
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: "monitoring-secrets"
              volumeMounts:
              - name: secrets-store
                mountPath: "/mnt/secrets-store"
                readOnly: true
              resources:
                requests:
                  memory: 2Gi
                  cpu: 500m
                limits:
                  memory: 4Gi
                  cpu: 1000m
            service:
              type: ClusterIP

          # AlertManager Configuration with Key Vault
          alertmanager:
            enabled: true
            serviceAccount:
              create: false
              name: monitoring-workload-identity
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: managed-csi
                    resources:
                      requests:
                        storage: 5Gi
              # Add workload identity labels and CSI volume
              podMetadata:
                labels:
                  azure.workload.identity/use: "true"
              volumes:
              - name: secrets-store
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: "monitoring-secrets"
              volumeMounts:
              - name: secrets-store
                mountPath: "/mnt/secrets-store"
                readOnly: true
              resources:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
                  cpu: 100m
            service:
              type: ClusterIP
            config:
              global:
                resolve_timeout: 5m
              route:
                group_by: ['alertname', 'cluster', 'service']
                group_wait: 10s
                group_interval: 10s
                repeat_interval: 12h
                receiver: 'default'
                routes:
                - match:
                    alertname: DeadMansSwitch
                  receiver: 'null'
              receivers:
              - name: 'default'
                webhook_configs:
                - url: 'http://localhost:5001/'
                  send_resolved: true
              - name: 'null'

          # Prometheus Operator with workload identity
          prometheusOperator:
            enabled: true
            serviceAccount:
              create: false
              name: monitoring-workload-identity
            # Add workload identity to operator pods
            podLabels:
              azure.workload.identity/use: "true"

          # Node Exporter
          nodeExporter:
            enabled: true

          # Kube State Metrics
          kubeStateMetrics:
            enabled: true

          # Default Rules and Alerts
          defaultRules:
            create: true
            rules:
              alertmanager: true
              etcd: true
              configReloaders: true
              general: true
              k8s: true
              kubeApiserver: true
              kubeApiserverAvailability: true
              kubeApiserverSlos: true
              kubelet: true
              kubeProxy: true
              kubePrometheusGeneral: true
              kubePrometheusNodeRecording: true
              kubernetesApps: true
              kubernetesResources: true
              kubernetesStorage: true
              kubernetesSystem: true
              network: true
              node: true
              nodeExporterAlerting: true
              nodeExporterRecording: true
              prometheus: true
              prometheusOperator: true

    # Source 2: Your custom manifests (ServiceMonitors, AlertRules, SecretProviderClass)
    - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
      targetRevision: HEAD
      path: manifests/monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Prune=false:ConfigMap:azure-config
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m