apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  # Manifests for SecretProviderClass and ServiceAccount
  - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
    targetRevision: HEAD
    path: manifests/nifi
  # Helm chart with proper structure
  - repoURL: https://cetic.github.io/helm-charts
    targetRevision: "1.2.1"
    chart: nifi
    helm:
      values: |
        # Basic configuration
        replicaCount: 1

        image:
          repository: apache/nifi
          tag: "1.23.2"
          pullPolicy: IfNotPresent

        # CORRECT way to configure single user auth for this chart
        singleUser:
          username: admin
          password: ""  # Will be overridden by environment variable

        # Properties that the chart actually supports
        properties:
          sensitiveKey: ""  # Will be overridden by environment variable
          algorithm: "NIFI_PBKDF2_AES_GCM_256"
          webProxyHost: "nifi-prod.data-platform.local"
          isNode: false

        # Use the service account from our manifests
        serviceAccount:
          create: false
          name: nifi-workload-identity

        # Configure secrets using the chart's secret structure
        secrets:
          - name: nifi-secrets
            keys:
              - admin-password
              - sensitive-key
              - keystore-password
              - truststore-password
            mountPath: /opt/nifi/nifi-current/secrets

        # Extra environment variables (chart supports this)
        extraEnvs:
          - name: NIFI_SENSITIVE_PROPS_KEY
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: sensitive-key
          - name: SINGLE_USER_CREDENTIALS_USERNAME
            value: "admin"
          - name: SINGLE_USER_CREDENTIALS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: admin-password
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: keystore-password
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: truststore-password

        # Extra volumes for secret provider class
        extraVolumes:
          - name: secrets-store
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "nifi-secrets"

        # Extra volume mounts
        extraVolumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true

        # Add labels for workload identity
        podLabels:
          azure.workload.identity/use: "true"

        # Resources
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1500m
            memory: 3Gi

        # JVM settings
        jvmMemory: 2g

        # Persistence
        persistence:
          enabled: true
          size: 50Gi

        # Service
        service:
          type: ClusterIP
          httpsPort: 8443

        # Zookeeper
        zookeeper:
          enabled: true
          replicaCount: 3

        # Security context
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

        # Startup probe with longer timeout
        startupProbe:
          enabled: true
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 30

        # Readiness probe
        readinessProbe:
          enabled: true
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        # Liveness probe
        livenessProbe:
          enabled: true
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3

  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 15m