apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  # Manifests for SecretProviderClass and ServiceAccount
  - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
    targetRevision: HEAD
    path: manifests/nifi
  # Helm chart
  - repoURL: https://cetic.github.io/helm-charts
    targetRevision: "1.2.1"
    chart: nifi
    helm:
      values: |
        # Use workload identity service account
        sts:
          serviceAccount:
            create: false
            name: nifi-workload-identity
        
        # PRODUCTION CONFIGURATION
        replicaCount: 1

        image:
          repository: apache/nifi
          tag: "1.23.2"
          pullPolicy: IfNotPresent

        # Use secrets from Key Vault
        properties:
          sensitiveKey: ""  # Will be set via environment variable
          algorithm: NIFI_PBKDF2_AES_GCM_256
          externalSecure: false
          httpsPort: 8443
          webProxyHost: "nifi-prod.data-platform.local"
          isNode: false
          clusterPort: 6007

        # SSL Configuration using secrets
        auth:
          admin: "CN=admin,OU=NIFI"
          SSL:
            keystorePasswd: ""  # Will be set via environment variable
            truststorePasswd: ""  # Will be set via environment variable
          singleUser:
            username: admin
            password: ""  # Will be set via environment variable

        # Add workload identity labels and secret volumes
        sts:
          pod:
            labels:
              azure.workload.identity/use: "true"
            volumes:
            - name: secrets-store
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "nifi-secrets"
            volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
            env:
            - name: NIFI_SENSITIVE_PROPS_KEY
              valueFrom:
                secretKeyRef:
                  name: nifi-secrets
                  key: sensitive-key
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nifi-secrets
                  key: keystore-password
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nifi-secrets
                  key: truststore-password
            - name: SINGLE_USER_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nifi-secrets
                  key: admin-password

        # PERSISTENCE CONFIGURATION
        persistence:
          enabled: true
          accessModes: [ReadWriteOnce]
          subPath:
            enabled: true
            name: data
            size: 50Gi

        # PRODUCTION RESOURCES
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 2000m
            memory: 4Gi

        jvmMemory: 4g

        service:
          type: ClusterIP
          httpsPort: 8443

        securityContext:
          runAsUser: 1000
          fsGroup: 1000

        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 15m
  revisionHistoryLimit: 3