apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  # Manifests for SecretProviderClass and ServiceAccount
  - repoURL: https://github.com/AzizBenDhiab/aks-data-platform-gitops.git
    targetRevision: HEAD
    path: manifests/nifi
  # Helm chart with CORRECTED configuration
  - repoURL: https://cetic.github.io/helm-charts
    targetRevision: "1.2.1"
    chart: nifi
    helm:
      values: |
        replicaCount: 3

        image:
          repository: apache/nifi
          tag: "1.23.2"
          pullPolicy: IfNotPresent

        # Properties configuration
        properties:
          sensitiveKey: "temporaryKey123456789"
          algorithm: "NIFI_PBKDF2_AES_GCM_256"
          webProxyHost: "nifi-prod.data-platform.local"
          isNode: false

        # FIXED: Correct service account structure for StatefulSet
        sts:
          serviceAccount:
            create: false
            name: nifi-workload-identity
          # FIXED: Pod annotations moved to correct location
          pod:
            annotations:
              azure.workload.identity/use: "true"

        # FIXED: Environment variables structure
        env:
          - name: NIFI_SENSITIVE_PROPS_KEY
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: sensitive-key
          - name: SINGLE_USER_CREDENTIALS_USERNAME
            value: "admin"
          - name: SINGLE_USER_CREDENTIALS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: admin-password
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: keystore-password
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nifi-secrets
                key: truststore-password

        # REMOVED: Invalid 'secrets' configuration
        # The Helm chart doesn't have a 'secrets' section like this
        # Secrets are handled via extraVolumes and env variables

        # FIXED: Extra volumes for CSI secret store
        extraVolumes:
          - name: secrets-store
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "nifi-secrets"

        # FIXED: Extra volume mounts
        extraVolumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true

        # Resources configuration
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1500m
            memory: 3Gi

        # FIXED: JVM memory configuration (correct parameter name)
        jvmMemory: 2g

        # Persistence configuration
        persistence:
          enabled: true
          # FIXED: Use subPath for single volume instead of separate volumes
          subPath:
            enabled: true
            name: nifi-data
            size: 50Gi

        # FIXED: Service configuration
        service:
          type: ClusterIP
          # REMOVED: httpsPort - use properties.httpsPort instead
          annotations: {}

        # FIXED: Properties configuration for HTTPS
        properties:
          sensitiveKey: "temporaryKey123456789"
          algorithm: "NIFI_PBKDF2_AES_GCM_256"
          webProxyHost: "nifi-prod.data-platform.local"
          isNode: false
          httpsPort: 8443  # MOVED: HTTPS port goes in properties
          httpPort: null   # Disable HTTP when using HTTPS

        # Zookeeper configuration
        zookeeper:
          enabled: true
          replicaCount: 3

        # FIXED: Security context
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

        # FIXED: Probes configuration (correct parameter names)
        startupProbe:
          enabled: true
          failureThreshold: 30
          periodSeconds: 15
          # REMOVED: initialDelaySeconds (not available for startupProbe in this chart)

        readinessProbe:
          # Note: Chart uses livenessProbe and readinessProbe differently
          # Check chart values.yaml for exact parameters

        livenessProbe:
          # Note: Chart may have different probe configuration
          # Check chart values.yaml for exact parameters

  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 15m