# argocd/nifi-test-app.yaml - HTTP ONLY VERSION
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cetic.github.io/helm-charts
    targetRevision: "1.2.1"
    chart: nifi
    helm:
      values: |
        replicaCount: 1

        image:
          repository: apache/nifi
          tag: "1.23.2"
          pullPolicy: IfNotPresent

        persistence:
          enabled: true
          storageClass: "managed-csi"
          accessMode: ReadWriteOnce
          size: 3Gi

        service:
          type: ClusterIP
          httpPort: 8080
          httpsPort: null

        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            memory: 1Gi
            cpu: 500m

        # DISABLE SSL COMPLETELY
        properties:
          isSecure: false
          httpPort: 8080
          httpsPort: ""
          webProxyHost: ""
          needClientAuth: false
          webHttpsHost: ""
          webHttpHost: "0.0.0.0"

        # Simple authentication
        auth:
          singleUser:
            username: admin
            password: admin123

        # Disable clustering to avoid complexity
        zookeeper:
          enabled: false
          
        # Reduce storage requirements
        persistence:
          size: 3Gi
          
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-test
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
