apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://cetic.github.io/helm-charts
    targetRevision: "1.2.1"
    chart: nifi
    helm:
      values: |
        replicaCount: 1

        image:
          repository: apache/nifi
          tag: "1.23.2"
          pullPolicy: IfNotPresent

        # Simple single user authentication - NO SECRETS FOR NOW
        auth:
          singleUser:
            username: admin
            password: "NiFiAdmin123!"  # Strong password, properly quoted

        # Properties configuration with valid values
        properties:
          algorithm: NIFI_PBKDF2_AES_GCM_256
          sensitiveKey: "NiFiSensitiveKey123456789"  # Must be at least 12 chars
          webProxyHost: "nifi-prod.data-platform.local"

        # Simple service account - using default for now
        sts:
          serviceAccount:
            create: true
            name: nifi-prod

        persistence:
          enabled: true
          size: 50Gi
          accessModes: [ReadWriteOnce]

        # Reasonable resource limits
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi

        jvmMemory: 2g

        service:
          type: ClusterIP
          httpsPort: 8443

        # Probes with reasonable timeouts
        startupProbe:
          httpGet:
            path: /nifi
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 20

        readinessProbe:
          httpGet:
            path: /nifi
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /nifi
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3

        # Disable Zookeeper clustering for simplicity
        zookeeper:
          enabled: false
          
        # Single node configuration
        properties:
          algorithm: NIFI_PBKDF2_AES_GCM_256
          sensitiveKey: "NiFiSensitiveKey123456789"
          webProxyHost: "nifi-prod.data-platform.local"
          isNode: false  # Single node, not clustered

  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m