apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgresql-secrets
  namespace: joget
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "__AZURE_CLIENT_ID__" # "__AZURE_CLIENT_ID__"
    keyvaultName: "__AZURE_KEYVAULT_NAME__" # "__AZURE_KEYVAULT_NAME__"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: postgres-admin-password
          objectType: secret
        - |
          objectName: joget-user-password
          objectType: secret
        - |
          objectName: joget-database
          objectType: secret
        - |
          objectName: joget-username
          objectType: secret
    tenantId: "__AZURE_TENANT_ID__" # "__AZURE_TENANT_ID__"
  secretObjects:
  - secretName: postgresql-secrets
    type: Opaque
    data:
    - objectName: postgres-admin-password
      key: postgres-password
    - objectName: joget-user-password
      key: user-password
    - objectName: joget-database
      key: database
    - objectName: joget-username
      key: username